const lat=44.421; const lon=11.978;
const WMO={0:'Sereno',1:'Prevalentemente sereno',2:'Parzialmente nuvoloso',3:'Coperto',45:'Nebbia',48:'Nebbia con brina',51:'Pioviggine debole',53:'Pioviggine',55:'Pioviggine intensa',61:'Pioggia debole',63:'Pioggia',65:'Pioggia intensa',80:'Rovesci deboli',81:'Rovesci',82:'Rovesci forti',95:'Temporale',96:'Temporale con grandine',99:'Temporale forte'};
const $=id=>document.getElementById(id);
async function clearOldCaches(){try{if('serviceWorker' in navigator){const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs){await r.unregister();}} if('caches' in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)));}}catch(e){console.warn(e)}}
function riskFrom(code,precip,humidity,wind,pressure){let score=12;if([95,96,99].includes(code))score+=55;if([80,81,82,61,63,65].includes(code))score+=25;if(precip>2)score+=18; if(humidity>80)score+=12;if(wind>28)score+=10;if(pressure<1009)score+=10;score=Math.min(100,Math.round(score));let level='tranquillo',emoji='🟢',title='Situazione tranquilla',text='Nessun segnale pesante nelle prossime ore.';if(score>=70){level='attenzione';emoji='🔴';title='Attenzione meteo';text='Segnali favorevoli a pioggia/temporali. Da monitorare spesso.'}else if(score>=48){level='da monitorare';emoji='🟠';title='Da monitorare';text='Qualche segnale di instabilità. Controlla radar e cielo.'}else if(score>=30){level='variabile';emoji='🟡';title='Situazione variabile';text='Non critica, ma può cambiare se si sviluppano nubi.'}return{score,level,emoji,title,text}}
function renderTimeline(hours,codes,precips){const wrap=$('timelineRow');wrap.innerHTML='';for(let i=0;i<4;i++){const code=codes[i]??0;const p=precips[i]??0;const risk=riskFrom(code,p,80,5,1015);const d=document.createElement('div');d.className='riskItem';d.innerHTML=`<b>${risk.emoji}</b><span>+${i+1}h</span><strong>${risk.level}</strong>`;wrap.appendChild(d)}}
function renderHours(times,temps,precipProb,precip){const wrap=$('hourGrid');wrap.innerHTML='';for(let i=0;i<8;i++){const d=new Date(times[i]);const hh=d.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});const item=document.createElement('div');item.className='hourItem';item.innerHTML=`<span>${hh}</span><strong>${Math.round(temps[i])}°</strong><small>${precipProb[i]||0}% · ${(precip[i]||0).toFixed(1)}mm</small>`;wrap.appendChild(item)}}
async function loadWeather(){try{await clearOldCaches();const url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m,pressure_msl&hourly=temperature_2m,precipitation_probability,precipitation,weather_code&timezone=Europe%2FRome&forecast_days=2`;const res=await fetch(url,{cache:'no-store'});const data=await res.json();const c=data.current;const h=data.hourly;const rain6=(h.precipitation||[]).slice(0,6).reduce((a,b)=>a+(b||0),0);const r=riskFrom(c.weather_code,rain6,c.relative_humidity_2m,c.wind_speed_10m,c.pressure_msl);$('temp').textContent=Math.round(c.temperature_2m*10)/10;$('desc').textContent=`${WMO[c.weather_code]||'Meteo disponibile'} · percepita ${Math.round(c.apparent_temperature*10)/10}°C`;$('humidity').textContent=`${c.relative_humidity_2m}%`;$('wind').textContent=`${Math.round(c.wind_speed_10m)} km/h`;$('rain').textContent=`${rain6.toFixed(1)} mm`;$('pressure').textContent=`${Math.round(c.pressure_msl)} hPa`;$('conteIndex').textContent=r.score;$('conteLevel').textContent=r.level;$('riskTitle').textContent=`${r.emoji} ${r.title}`;$('riskText').textContent=r.text;$('quickTitle').textContent=r.score>=48?'Occhio, da seguire':'Per ora abbastanza tranquilla';$('quickText').textContent=r.text;$('updated').textContent='Aggiornato '+new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});renderTimeline(h.time.slice(1,5),h.weather_code.slice(1,5),h.precipitation.slice(1,5));renderHours(h.time.slice(1,9),h.temperature_2m.slice(1,9),h.precipitation_probability.slice(1,9),h.precipitation.slice(1,9));$('analysisText').textContent='';}catch(e){$('riskTitle').textContent='Dati non disponibili';$('riskText').textContent='Connessione o API meteo momentaneamente non raggiungibile.';console.error(e)}}
$('refreshBtn').addEventListener('click',loadWeather);$('analyzeBtn').addEventListener('click',()=>{$('analysisText').textContent='Sintesi Conte: controlla radar e fulmini se l’indice supera 50. Se pressione cala, umidità alta e compaiono nuclei su Appennino/Faentino, tieni d’occhio le prossime 1-3 ore.'});loadWeather();
