const LAT=44.42, LON=11.98;
const API=`https://api.open-meteo.com/v1/forecast?latitude=${LAT}&longitude=${LON}&current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,pressure_msl,wind_speed_10m,wind_direction_10m,wind_gusts_10m&hourly=temperature_2m,precipitation_probability,precipitation,weather_code,relative_humidity_2m,wind_gusts_10m,pressure_msl,dew_point_2m&forecast_days=1&timezone=Europe%2FRome`;
const $=id=>document.getElementById(id);
const codeMap={0:['Sereno','☀️'],1:['Prevalentemente sereno','🌤️'],2:['Parzialmente nuvoloso','⛅'],3:['Nuvoloso','☁️'],45:['Nebbia','🌫️'],48:['Nebbia','🌫️'],51:['Pioviggine','🌦️'],53:['Pioviggine','🌦️'],55:['Pioviggine','🌦️'],61:['Pioggia debole','🌧️'],63:['Pioggia','🌧️'],65:['Pioggia intensa','🌧️'],80:['Rovesci','🌦️'],81:['Rovesci','🌧️'],82:['Rovesci forti','⛈️'],95:['Temporale','⛈️'],96:['Temporale/grandine','⛈️'],99:['Temporale/grandine','⛈️']};
function fmt(n,d=0){return Number.isFinite(n)?n.toFixed(d):'--'}
function setDot(el,level){el.className='dot '+level} function setBig(level){$('bigDot').className='bigdot '+level}
function riskColor(score){return score>=75?'red':score>=50?'orange':score>=25?'yellow':'green'}
function riskLabel(score){return score>=75?'alto':score>=50?'attenzione':score>=25?'da monitorare':'tranquillo'}
function calcIndex(current,hours){const rainMax=Math.max(...hours.map(h=>h.pop||0));const acc=hours.reduce((s,h)=>s+(h.rain||0),0);const gust=Math.max(current.wind_gusts_10m||0,...hours.map(h=>h.gust||0));const hum=current.relative_humidity_2m||0;const press=current.pressure_msl||1015;let s=0;s+=Math.min(35,rainMax*.35);s+=Math.min(25,acc*8);if(hum>70)s+=(hum-70)*.55;if(gust>35)s+=(gust-35)*.6;if(press<1008)s+=(1008-press)*1.2;return Math.round(Math.max(0,Math.min(100,s)))}
function makeHours(data){const now=new Date();let arr=[];for(let i=0;i<data.hourly.time.length;i++){const t=new Date(data.hourly.time[i]);if(t>=now && arr.length<7){arr.push({time:t,temp:data.hourly.temperature_2m[i],pop:data.hourly.precipitation_probability[i],rain:data.hourly.precipitation[i],code:data.hourly.weather_code[i],hum:data.hourly.relative_humidity_2m[i],gust:data.hourly.wind_gusts_10m[i],press:data.hourly.pressure_msl[i],dew:data.hourly.dew_point_2m[i]})}}return arr}
function renderTimeline(hours){$('riskTimeline').innerHTML=hours.slice(0,4).map((h,i)=>{let sc=Math.min(100,(h.pop||0)*.5+(h.rain||0)*15+((h.hum||0)>70?((h.hum-70)*.4):0));let c=riskColor(sc);return `<div class="risk-item"><span class="dot ${c}"></span><span>+${i+1}h</span><b>${riskLabel(sc)}</b></div>`}).join('')}
function renderHours(hours){$('hourlyGrid').innerHTML=hours.map(h=>{const [desc,ic]=codeMap[h.code]||['Meteo','🌡️'];return `<div class="hour"><div class="t">${h.time.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</div><b>${fmt(h.temp)}°</b><div>${ic}</div><div class="p">${h.pop||0}% · ${fmt(h.rain,1)}mm</div></div>`}).join('')}
function decision(score,hours,current){const rainMax=Math.max(...hours.map(h=>h.pop||0));const gust=Math.max(current.wind_gusts_10m||0,...hours.map(h=>h.gust||0));if(score>=70)return ['Attenzione alta','Controlla subito Radar ER, Fulmini, Allerte e Lamone. Situazione da seguire.'];
if(score>=45)return ['Da monitorare','Possibili rovesci o temporali. Tieni d’occhio Appennino, radar e fulmini.'];
if(score>=22)return ['Occhio più tardi','Non è critica, ma qualche segnale c’è. Ricontrolla nelle prossime ore.'];
return ['Per ora abbastanza tranquilla',`Pioggia max 6h ${rainMax}%, raffica max ${fmt(gust)} km/h. Giornata gestibile.`]}
function render(data){const c=data.current;const hours=makeHours(data);const [desc,icon]=codeMap[c.weather_code]||['Meteo','🌡️'];const score=calcIndex(c,hours);const color=riskColor(score);const label=riskLabel(score);$('weatherIcon').textContent=icon;$('headTemp').textContent=`${fmt(c.temperature_2m,1)}°`;$('tempNow').textContent=fmt(c.temperature_2m,1);$('weatherDesc').textContent=`${desc} · ${Math.max(...hours.map(h=>h.pop||0))}% pioggia max 6h`;$('feels').textContent=`${fmt(c.apparent_temperature,1)}°`;$('humidity').textContent=`${fmt(c.relative_humidity_2m)}%`;$('dew').textContent=`${fmt(hours[0]?.dew,1)}°`;$('wind').textContent=`${fmt(c.wind_speed_10m)} km/h`;$('gust').textContent=`${fmt(c.wind_gusts_10m)} km/h`;$('pressure').textContent=`${fmt(c.pressure_msl)} hPa`;$('rain6').textContent=`${fmt(hours.reduce((s,h)=>s+(h.rain||0),0),1)} mm`;$('conteIndex').textContent=score;$('conteLevel').textContent=label;$('statusTitle').textContent=score<25?'Tranquilla':score<50?'Da monitorare':score<75?'Attenzione':'Alta attenzione';$('statusText').textContent=score<25?'Nessun segnale pesante nelle prossime ore.':score<50?'Qualche segnale: controlla evoluzione e radar.':score<75?'Situazione da seguire con attenzione.':'Apri subito radar, allerte e fiumi.';setBig(color);setDot($('dotMeteo'),color);setDot($('dotTemporali'),score>=50?'yellow':'green');const [dt,dx]=decision(score,hours,c);$('decisionTitle').textContent=dt;$('decisionText').textContent=dx;$('updatedAt').textContent=new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});renderTimeline(hours);renderHours(hours);$('analysisBox').innerHTML=`<b>Analisi rapida</b><br>Indice Conte ${score}/100: ${label}. Pioggia max prossime ore ${Math.max(...hours.map(h=>h.pop||0))}%, accumulo stimato ${fmt(hours.reduce((s,h)=>s+(h.rain||0),0),1)} mm. Umidità ${fmt(c.relative_humidity_2m)}%, pressione ${fmt(c.pressure_msl)} hPa. Per decisione reale: se il cielo cambia, apri Radar ER, Fulmini, Allerte e Lamone.`}
async function load(){try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw new Error('api');const data=await r.json();render(data)}catch(e){$('statusTitle').textContent='Dati non disponibili';$('statusText').textContent='Controlla connessione o riprova. Link rapidi e Lamone restano disponibili.';$('decisionTitle').textContent='Valuto...';$('decisionText').textContent='Sintesi non disponibile senza dati meteo.';$('conteIndex').textContent='--';}}
$('refreshBtn').addEventListener('click',load);$('analyzeBtn').addEventListener('click',()=>{$('analysisBox').classList.toggle('hidden')});
if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister()));}
load();
